export const GET_BRANDS="GET_BRANDS";
export const GET_BRANDS_SUCCESS="GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE="GET_BRANDS_FAILURE";
// export const GET_BRANDS_BRANDSIDS="GET_BRANDS_FAILURE";