export const CHANGE_INPUT ="CHANGE_INPUT";

export const LOGIN_SUBMIT ="LOGIN_SUBMIT";
export const LOGIN_SUBMIT_SUCCESS ="LOGIN_SUBMIT_SUCCESS";
export const LOGIN_SUBMIT_FAILURE ="LOGIN_SUBMIT_FAILURE";