export const CHANGE_SIGNUP_INPUT ="CHANGE_SIGNUP_INPUT";
export const SIGNUP_SUBMIT ="SIGNUP_SUBMIT";
export const SIGNUP_SUBMIT_SUCCESS ="SIGNUP_SUBMIT_SUCCESS";
export const SIGNUP_SUBMIT_FAILURE ="SIGNUP_SUBMIT_FAILURE";